
class Processor(object):
    # trials_classification
    DRANK = 1
    NOT_DRANK = 2
    ATE = 3
    NOT_ATE = 4
    NEUTRAL = 5
    OMISSION_WATER = 6
    OMISSION_PELLET = 7
    OMISSION_FOOD_TASTE = 8
    PROBLEM = 9
    SURPRISE_FLUID = 10
    SURPRISE_PELLET = 11
    FLUID_INSTEAD_OF_PELLET = 12
    PELLET_INSTEAD_OF_FLUID = 13
    DRANK_LIGHT = 14
    NOT_DRANK_LIGHT = 15
    NEUTRAL_LIGHT = 16
    ATE_LIGHT = 17
    NOT_ATE_LIGHT = 18
    OPTO_TRIGGER = 19
    OMISSION_FLUID_LIGHT = 20
    OMISSION_PELLET_LIGHT = 21
    DRANK_BETWEEN_LIGHT = 22
    OMISSION_FLUID_BETWEEN_LIGHT = 23
    ATE_BETWEEN_LIGHT = 24
    OMISSION_PELLET_BETWEEN_LIGHT = 25
    NEUTRAL_BETWEEN_LIGHT = 26
    NOT_DRANK_BETWEEN_LIGHT = 27
    NOT_ATE_BETWEEN_LIGHT = 28
    NOT_ATE_LICKED = 29

    # general configurations
    CUES_TYPE = 'regular'
    SEC_PRE_TRIAL = 2
    CUE_DURATION = 2
    SEC_HZ = None
    FLAT_SEC = 30

    def __init__(
        self,
        drank=DRANK,
        not_drank=NOT_DRANK,
        ate=ATE,
        not_ate=NOT_ATE,
        neutral=NEUTRAL,
        omission_water=OMISSION_WATER,
        omission_pellet=OMISSION_PELLET,
        surprise_fluid=SURPRISE_FLUID,
        surprise_pellet=SURPRISE_PELLET,
        omission_food_taste=OMISSION_FOOD_TASTE,
        problem=PROBLEM,
        pellet_instead_of_fluid=PELLET_INSTEAD_OF_FLUID,
        fluid_instead_of_pellet=FLUID_INSTEAD_OF_PELLET,
        drank_light=DRANK_LIGHT,
        drank_between_light=DRANK_BETWEEN_LIGHT,
        not_drank_light=NOT_DRANK_LIGHT,
        not_drank_between_light=NOT_DRANK_BETWEEN_LIGHT,
        omission_fluid_light=OMISSION_FLUID_LIGHT,
        omission_fluid_between_light=OMISSION_FLUID_BETWEEN_LIGHT,
        omission_pellet_light=OMISSION_PELLET_LIGHT,
        omission_pellet_between_light=OMISSION_PELLET_BETWEEN_LIGHT,
        neutral_light=NEUTRAL_LIGHT,
        neutral_between_light=NEUTRAL_BETWEEN_LIGHT,
        ate_light=ATE_LIGHT,
        ate_between_light=ATE_BETWEEN_LIGHT,
        not_ate_light=NOT_ATE_LIGHT,
        not_ate_between_light=NOT_ATE_BETWEEN_LIGHT,
        not_ate_licked=NOT_ATE_LICKED,
        opto_trigger=OPTO_TRIGGER,
        sec_hz=SEC_HZ,
        sec_pre_trial=SEC_PRE_TRIAL,
        cue_duration=CUE_DURATION,
        flat_sec=FLAT_SEC,
    ):
        self.pellet_signal = None
        self.fluid_signal = None
        self.omission_fluid_signal = None
        self.omission_pellet_signal = None
        self.neutral_signal = None
        self.neutral_light_off_signal = None
        self.surprise_fluid_signal = None
        self.surprise_pellet_signal = None
        self.pellet_instead_of_fluid_signal = None
        self.fluid_instead_of_pellet_signal = None
        self.opto_trigger_signal = None
        self.fluid_light_signal = None
        self.neutral_light_signal = None
        self.neutral_light_omission_signal = None
        self.pellet_light_signal = None
        self.pellet_light_O_signal = None
        self.pellet_light_off_signal = None

        self.drank = drank
        self.not_drank = not_drank
        self.ate = ate
        self.not_ate = not_ate
        self.neutral = neutral
        self.omission_water = omission_water
        self.omission_pellet = omission_pellet
        self.omission_food_taste = omission_food_taste
        self.problem = problem
        self.surprise_fluid = surprise_fluid
        self.surprise_pellet = surprise_pellet
        self.pellet_instead_of_fluid = pellet_instead_of_fluid
        self.fluid_instead_of_pellet = fluid_instead_of_pellet
        self.drank_light = drank_light
        self.drank_between_light = drank_between_light
        self.not_drank_light = not_drank_light
        self.not_drank_between_light = not_drank_between_light
        self.omission_fluid_light = omission_fluid_light
        self.omission_fluid_between_light = omission_fluid_between_light
        self.neutral_light = neutral_light
        self.neutral_between_light = neutral_between_light
        self.ate_light = ate_light
        self.ate_between_light = ate_between_light
        self.not_ate_light = not_ate_light
        self.not_ate_between_light = not_ate_between_light
        self.omission_pellet_light = omission_pellet_light
        self.omission_pellet_between_light = omission_pellet_between_light
        self.opto_trigger = opto_trigger
        self.not_ate_licked = not_ate_licked

        self.sec_hz = sec_hz
        self.sec_pre_trial = sec_pre_trial
        self.cue_duration = cue_duration
        self.flat_sec = flat_sec
